---

- name: Download install nodejs script
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.31.7/install.sh
    dest: /tmp/nvm-install.sh
    mode: 0744
    checksum: md5:64b6b338ca036c8637e256d15f832206

- name: Run the shell script with additional environment values
  script: /tmp/nvm-install.sh
  environment:
    NVM_DIR: /home/dorwi/Installs/.nvm