---

- name: Install Git
  apt: name=git state=latest
  become: true

- name: Add wheezy backports source
  lineinfile: 
    dest: /etc/apt/sources.list.d/wheezy-backports-main.list
    state: present
    create: yes
    line: deb http://http.debian.net/debian wheezy-backports main
  become: true

- name: Download the git lfs installer
  get_url:
    url: https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh
    dest: /tmp/git.lfs.script.deb.sh
    mode: 0744
  become: true

- name: Run the git lfs installer
  script: /tmp/git.lfs.script.deb.sh
  become: true

- name: Install git-lfs package
  apt: name=git-lfs state=latest
  become: true

- name: Install git lfs
  command: git lfs install